spring:
  datasource:
    name: aishuati  #????
    url: jdbc:mysql://114.55.177.229:3306/aishuati?useUnicode=true&useSSL=false&serverTimezone = GMT #url
    username: root  #???
    password: root  #??
    driver-class-name: com.mysql.cj.jdbc.Driver  #???????
mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.example.aishuati.JavaBean #配置实体类